### ISSUE TITLE
accelerer l'import ldif

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/sambaedu-config#1]
Il faut mettre le DB_CONFIG suivant : 
```
set_cachesize 	0	41943040	0
set_flags       DB_TXN_NOSYNC
set_lg_bsize	524288
set_lk_max_objects      10000
set_lk_max_locks        10000
set_lk_max_lockers      10000
set_flags DB_LOG_AUTOREMOVE
```

Pour un gros annuaire, l'import passe de quelques minutes à quelques secondes !

**Comment by mollef** [comment]
https://github.com/SambaEdu/sambaedu-config/commit/c646ccb331d54b7150e4c03f91d095620c41b7b6
