### ISSUE TITLE
renommer la branche "people"

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/sambaedu-config#3]
Actuellement on l'a nommée ou=users, or avec certains outils externes cela pose problème car il existe un cn=users qui est pris en compte par les filtres ldap

Le mieux serait de la nommer 
OU=Utilisateurs, comme cela pas d'ambiguité.

**Comment by mollef** [comment]
https://github.com/SambaEdu/sambaedu-config/commit/64cbfbd2c2874ed056b1cb0114c8624277c5162e
https://github.com/SambaEdu/sambaedu-config/commit/fec51185a8bce758f65542c1adae37849c624277
